# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_tittle',
            new_name='album_title',
        ),
    ]
